name: Continuous Deployment - Sonar Analisys & Deploy to Heroku on push to Main Branch

on:
  push:
    branches: [ main ]
    
jobs:         
  test_and_sonar_analisys:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Analyze with SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  deploy: 
    needs: [ test_and_sonar_analisys ]
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: "app-my-contact-backend"
                heroku_email: "nilsenn.bianca@gmail.com"